package com.app.model;

public enum NotificationType {
    BOOKING_REQUESTED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_REMINDER,
    SYSTEM_ALERT,
    ANNOUNCEMENT,
    MANUAL,
    DIGEST,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_UPDATED,
    TICKET_COMMENT_ADDED,
    TICKET_RESOLVED,
    TICKET_CLOSED,
    TICKET_REJECTED
}
